### ISSUE TITLE
Class 'Kachkaev\PHPR\Engine\AbstractREngine' not found

### ISSUE THREAD

**Issue by gitbobo** [kachkaev/php-r#33]
Fatal error: Class 'Kachkaev\PHPR\Engine\AbstractREngine' not found in /home/websites/test/www/src/Kachkaev/PHPR/Engine/CommandLineREngine.php on line 7  
I am using centos 6,composer1.51.  
Do you use exec() to run R script?

**Comment by kachkaev** [comment]
Hi @gitbobo! Sorry to hear that. Do you think your issue can be similar to https://github.com/kachkaev/php-r/issues/22?

If you can't solve the problem by tweaking the way you autoload and import the classes, please paste your code here.


> Do you use exec() to run R script?
The library uses a child PHP process, details here: https://github.com/kachkaev/php-r/blob/master/src/Kachkaev/PHPR/Process/CommandLineRProcess.php

**Comment by gitbobo** [comment]
Hi@kachkaev,thanks for your reply!
I still figure this problem,it seemed related to framework, it's ok with symfony, but there's something wrong with yii.  
May I ask a question,compare to exec(), what's the advantage of php-r?
It seemed exec() can do everything php-r can do

**Comment by kachkaev** [comment]
> May I ask a question,compare to exec(), what's the advantage of php-r?

I think the advantages depend on your task. If you simply want to execute a static R file from PHP, then just `exec()` is probably enough. However, when it comes to customizing the input or parsing the output, the library becomes quite useful as it saves you from implementing a lot of low-level stuff.

> I still figure this problem,it seemed related to framework, it's ok with symfony

Good luck with that! Feel free to share your findings here so that others could take a shortcut!
