### ISSUE TITLE
how I can display plot?

### ISSUE THREAD

**Issue by dipenpatel235** [kachkaev/php-r#40]
hello,

I have written small plot barchart R code.
now i want to execute that code using your library so how I can see Plot generated by R on php webpage?
please check below code :-

```
<?php
require_once 'vendor/autoload.php';
use Kachkaev\PHPR\RCore;
use Kachkaev\PHPR\Engine\CommandLineREngine;

$r = new RCore(new CommandLineREngine('/usr/bin/R'));
echo var_dump($r);
$result = $r->run(<<<EOF

responses = c(25, 44, 29, 60, 76, 4, 11, 33, 34, 22, 22, 11, 11, 89)
barplot(responses)
EOF
 );

echo $result;
?>
```

Thanks

**Comment by kachkaev** [comment]
Hi @dipenpatel235. I am afraid that this is impossible directly, because PHP and R only exchange text. However, what you can get an image if you save your boxplot to a file with R code and then read that PNG in PHP.

I'll close this issue as it is a question rather than a bug report, but feel free to add more comments.
